"use client";
import { useEffect, useState } from "react";
import ContTitle from "@/components/title/ContTitle";
import YoutubeCont from "@/components/Youtube/YoutubeCont";
// import styles from "./page.module.scss";
// export const metadata = {
//   title: "Movie API",
//   description: "Generated by create Movie API",
// };

const Youtube = () => {
  const [youtubes, setYoutube] = useState([]);
  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://youtube.googleapis.com/youtube/v3/search?part=snippet&maxResults=30&q=science&type=video&key=AIzaSyA574D8uxBhHYpAp6Xu760fh7tV3Fitgh8"
      );
      if (!res.ok) {
        throw new Error("Faild tp fetch data");
      }
      const data = await res.json();
      setYoutube(data.items);
    };
    getData();
  }, []);
  console.log(youtubes);

  return (
    <>
      <ContTitle title="Youtube" />
      <YoutubeCont youtubes={youtubes} />
    </>
  );
};

export default Youtube;
