"use client";
import { useEffect, useState } from "react";
import ContTitle from "@/components/title/ContTitle";
import UnsplashCont from "@/components/unsplash/UnsplashCont";
// import styles from "./page.module.scss";
// export const metadata = {
//   title: "Movie API",
//   description: "Generated by create Movie API",
// };

const Unsplash = () => {
  const [unsplash, setUnsplash] = useState([]);
  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://api.unsplash.com/photos?client_id=q_Cs549hvK1mONfcPtht4An0-5wms_SlpsGWUO0nCtA&per_page=30"
      );
      if (!res.ok) {
        throw new Error("Faild tp fetch data");
      }
      const data = await res.json();
      setUnsplash(data);
    };
    getData();
  }, []);
  console.log(unsplash);

  return (
    <>
      <ContTitle title="unsplash" />
      <UnsplashCont unsplash={unsplash} />
    </>
  );
};

export default Unsplash;
