"use client";
import { useEffect, useState } from "react";
import ContTitle from "@/components/title/ContTitle";
import MovieCont from "@/components/movie/MovieCont";
// export const metadata = {
//   title: "Movie API",
//   description: "Generated by create Movie API",
// };

const Moive = () => {
  const [movies, setMovies] = useState([]);
  useEffect(() => {
    const getData = async () => {
      const res = await fetch(
        "https://api.themoviedb.org/3/movie/popular?api_key=d318289536044275f4abc5923f180d7f"
      );
      if (!res.ok) {
        throw new Error("Faild tp fetch data");
      }
      const data = await res.json();
      setMovies(data.results);
    };
    getData();
  }, []);
  console.log(movies);

  return (
    <>
      <ContTitle title="movie" />
      <MovieCont movies={movies} />
    </>
  );
};

export default Moive;
